### PR TITLE
Glyph addtion and anchor placement

### PR DESCRIPTION
**Pull request by girish-dalvi**
– Added glyph ktVSR (U+110C2) and anchors.
– In ktYa, KtVa changed position of Nukta to avoid clashing with ktVSR 
– In ktYa, corrected placement of anchor

### CODE REVIEW

**Comment by simoncozens** [comment]
Thank you for this. It looks generally OK, although the original Kaithi proposal notes that ka + vocalic r does not attach to the the stem but forms a ligature:

Screenshot 2023-07-10 at 08 54 11

See also other examples in the [vocalic r proposal](https://www.unicode.org/L2/L2020/20151-kaithi-vowel-sign-vocalic-r.pdf):

Screenshot 2023-07-10 at 08 55 23
Screenshot 2023-07-10 at 08 55 41

However, I notice that the "normal" form of ka + attached vocalic r does seem to also exist in the proposal, if I am reading it right (although the scan is not very clear):
Screenshot 2023-07-10 at 08 58 46

I feel like we may need a ligature ktKVSRA here.

**Comment by simoncozens** [comment]
There's also a missing space in the feature code, but obviously I can fix that:

```diff
--- a/sources/NotoSansKaithi.glyphs
+++ b/sources/NotoSansKaithi.glyphs
@@ -52,7 +52,7 @@ code = "ktBHa.half ktBa.half ktCHa.half ktCa.half ktDDDHa.half ktDDHa.half ktDDa
 name = class16;
 },
 {
-code = "ktVSCBindu ktVSAnusvara ktVSE  ktVSRktVSAI ktVSAIm ktVSEm ktRaHook ktRaAnusvara ktRaCandrabindu\012";
+code = "ktVSCBindu ktVSAnusvara ktVSE  ktVSR ktVSAI ktVSAIm ktVSEm ktRaHook ktRaAnusvara ktRaCandrabindu\012";
 name = markAttachmentSet11;
 },
 {
```

**Comment by girish-dalvi** [comment]
Hi Simon,

We have updated the file with ligatures for Ka+vocalicR, Ha+vocalicR and alternate form of Ka+vocalicR.
image

**Comment by simoncozens** [comment]
Thank you so much!

**Pull request merged**
